# Generated by Django 5.0.6 on 2024-05-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
