# Generated by Django 5.0.6 on 2024-05-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_admin', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='role_id',
        ),
    ]
