# Generated by Django 5.0.6 on 2024-05-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_admin', '0003_rename_role_role_role_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='user_id',
        ),
    ]
