# Generated by Django 5.0.6 on 2024-05-23 08:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_admin', '0004_rename_role_id_user_role_rename_user_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
