# Generated by Django 5.0.6 on 2024-05-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
