# Generated by Django 5.0.6 on 2024-05-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecfood_dish', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='image',
            new_name='ima_url',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='name_url',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dish',
        ),
    ]
